export const tagList = [
    { link: "#", name: "Engineering", },
    { link: "#", name: "Business Development", },
    { link: "#", name: "Finance", },
    { link: "#", name: "Administrative Assistant", },
    { link: "#", name: "Retail Associate", },
    { link: "#", name: "Customer Service", },
    { link: "#", name: "Operations", },
    { link: "#", name: "Information Technology", },
    { link: "#", name: "Marketing", },
    { link: "#", name: "Human Resources" },
    { link: "#", name: "Healthcare Service" },
    { link: "#", name: "Sales" },
    { link: "#", name: "Program and Project Management" },
    { link: "#", name: "Accounting" },
    { link: "#", name: "Arts and Design" },
    { link: "#", name: "Community and Social Services" },
    { link: "#", name: "Consulting" },
    { link: "#", name: "Education" },
    { link: "#", name: "Entrepreneurship" },
    { link: "#", name: "Legal" },
    { link: "#", name: "Media and Communication" },
    { link: "#", name: "Military and Protective Services" },
    { link: "#", name: "Product Management" },
    { link: "#", name: "Purchasing" },
    { link: "#", name: "Quality Assurance" },
    { link: "#", name: "Real Estate" },
    { link: "#", name: "Research" },
    { link: "#", name: "Support" },
    { link: "#", name: "Administrative" },
]